version: '3'
services:

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: of-failure
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    networks:
      - app-network

  mysql:
    image: mysql:5.7.22
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: mysql_pass    
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
